### PR TITLE
add pr to lualine

### PR DESCRIPTION
**Pull request by GustavEikaas**

### CODE REVIEW

**Comment by GustavEikaas** [comment]
comment

**Comment by GustavEikaas** [comment]
@GustavEikaas

**Comment by Gustav-Eikaas** [comment]
@GustavEikaas Will this notification go through?

**Review by Gustav-Eikaas — APPROVED** [review]

**Comment by Gustav-Eikaas** [comment]
test

**Comment by Gustav-Eikaas** [comment]
Yeah bro!

**Comment by Gustav-Eikaas** [comment]
hhmm

**Comment by Gustav-Eikaas** [comment]
testing....

**Pull request closed without merging**
